src/Entity/Hotel.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\HotelRepository")
 */
class Hotel
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $nom;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Ville", inversedBy="hotels")
     */
    private $ville;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $image;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $title;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $type;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $url;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $adult_only;

    
    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Chambrehotel", mappedBy="hotel")
     */
    private $chambres;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\VenteHotel", mappedBy="hotelId")
     */
    private $venteHotels;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Saison", mappedBy="id_hotel")
     */
    private $saisons;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\ContactHotel", mappedBy="id_hotel")
     */
    private $contactHotels;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\StopSales", mappedBy="id_hotel")
     */
    private $stopSales;

    public function __construct()
    {
        $this->chambres = new ArrayCollection();
        $this->venteHotels = new ArrayCollection();
        $this->saisons = new ArrayCollection();
        $this->contactHotels = new ArrayCollection();
        $this->stopSales = new ArrayCollection();
    }

   
    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(?string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getVille(): ?Ville
    {
        return $this->ville;
    }

    public function setVille(?Ville $ville): self
    {
        $this->ville = $ville;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(?string $image): self
    {
        $this->image = $image;

        return $this;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(?string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getType(): ?string
    {
        return $this->type;
    }

    public function setType(?string $type): self
    {
        $this->type = $type;

        return $this;
    }

    public function getUrl(): ?string
    {
        return $this->url;
    }

    public function setUrl(?string $url): self
    {
        $this->url = $url;

        return $this;
    }

    public function getAdultOnly(): ?bool
    {
        return $this->adult_only;
    }

    public function setAdultOnly(?bool $adult_only): self
    {
        $this->adult_only = $adult_only;

        return $this;
    }

    
    
    /**
     * @return Collection|Chambrehotel[]
     */
    public function getChambres(): Collection
    {
        return $this->chambres;
    }

    public function addChambre(Chambrehotel $chambre): self
    {
        if (!$this->chambres->contains($chambre)) {
            $this->chambres[] = $chambre;
            $chambre->setHotel($this);
        }

        return $this;
    }

    public function removeChambre(Chambrehotel $chambre): self
    {
        if ($this->chambres->contains($chambre)) {
            $this->chambres->removeElement($chambre);
            // set the owning side to null (unless already changed)
            if ($chambre->getHotel() === $this) {
                $chambre->setHotel(null);
            }
        }

        return $this;
    }

    public function __toString(){

        return $this->nom;
       
    }

    /**
     * @return Collection|VenteHotel[]
     */
    public function getVenteHotels(): Collection
    {
        return $this->venteHotels;
    }

    public function addVenteHotel(VenteHotel $venteHotel): self
    {
        if (!$this->venteHotels->contains($venteHotel)) {
            $this->venteHotels[] = $venteHotel;
            $venteHotel->setHotelId($this);
        }

        return $this;
    }

    public function removeVenteHotel(VenteHotel $venteHotel): self
    {
        if ($this->venteHotels->contains($venteHotel)) {
            $this->venteHotels->removeElement($venteHotel);
            // set the owning side to null (unless already changed)
            if ($venteHotel->getHotelId() === $this) {
                $venteHotel->setHotelId(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Saison[]
     */
    public function getSaisons(): Collection
    {
        return $this->saisons;
    }

    public function addSaison(Saison $saison): self
    {
        if (!$this->saisons->contains($saison)) {
            $this->saisons[] = $saison;
            $saison->setIdHotel($this);
        }

        return $this;
    }

    public function removeSaison(Saison $saison): self
    {
        if ($this->saisons->contains($saison)) {
            $this->saisons->removeElement($saison);
            // set the owning side to null (unless already changed)
            if ($saison->getIdHotel() === $this) {
                $saison->setIdHotel(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|ContactHotel[]
     */
    public function getContactHotels(): Collection
    {
        return $this->contactHotels;
    }

    public function addContactHotel(ContactHotel $contactHotel): self
    {
        if (!$this->contactHotels->contains($contactHotel)) {
            $this->contactHotels[] = $contactHotel;
            $contactHotel->setIdHotel($this);
        }

        return $this;
    }

    public function removeContactHotel(ContactHotel $contactHotel): self
    {
        if ($this->contactHotels->contains($contactHotel)) {
            $this->contactHotels->removeElement($contactHotel);
            // set the owning side to null (unless already changed)
            if ($contactHotel->getIdHotel() === $this) {
                $contactHotel->setIdHotel(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|StopSales[]
     */
    public function getStopSales(): Collection
    {
        return $this->stopSales;
    }

    public function addStopSale(StopSales $stopSale): self
    {
        if (!$this->stopSales->contains($stopSale)) {
            $this->stopSales[] = $stopSale;
            $stopSale->setIdHotel($this);
        }

        return $this;
    }

    public function removeStopSale(StopSales $stopSale): self
    {
        if ($this->stopSales->contains($stopSale)) {
            $this->stopSales->removeElement($stopSale);
            // set the owning side to null (unless already changed)
            if ($stopSale->getIdHotel() === $this) {
                $stopSale->setIdHotel(null);
            }
        }

        return $this;
    }

}

src/Form/HotelType.php
<?php

namespace App\Form;

use App\Entity\Hotel;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class HotelType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('nom')
            ->add('image')
            ->add('title')
            ->add('type')
            ->add('url')
            ->add('adult_only')
            ->add('ville')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Hotel::class,
        ]);
    }
}

src/Controller/HotelController.php
<?php

namespace App\Controller;

use App\Entity\Hotel;
use App\Form\HotelType;
use App\Repository\HotelRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/hotel")
 */
class HotelController extends AbstractController
{
    /**
     * @Route("/", name="hotel_index", methods={"GET"})
     */
    public function index(HotelRepository $hotelRepository): Response
    {
        return $this->render('hotel/index.html.twig', [
            'hotels' => $hotelRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="hotel_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $hotel = new Hotel();
        $form = $this->createForm(HotelType::class, $hotel);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($hotel);
            $entityManager->flush();

            return $this->redirectToRoute('hotel_index');
        }

        return $this->render('hotel/new.html.twig', [
            'hotel' => $hotel,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="hotel_show", methods={"GET"})
     */
    public function show(Hotel $hotel): Response
    {
        return $this->render('hotel/show.html.twig', [
            'hotel' => $hotel,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="hotel_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Hotel $hotel): Response
    {
        $form = $this->createForm(HotelType::class, $hotel);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('hotel_index');
        }

        return $this->render('hotel/edit.html.twig', [
            'hotel' => $hotel,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="hotel_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Hotel $hotel): Response
    {
        if ($this->isCsrfTokenValid('delete'.$hotel->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($hotel);
            $entityManager->flush();
        }

        return $this->redirectToRoute('hotel_index');
    }
}

templates/hotel/_delete_form.html.twig
<form method="post" action="{{ path('hotel_delete', {'id': hotel.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ hotel.id) }}">
    <button class="btn">Delete</button>
</form>

templates/hotel/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/hotel/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Hotel{% endblock %}

{% block body %}
    <h1>Edit Hotel</h1>

    {{ include('hotel/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('hotel_index') }}">back to list</a>

    {{ include('hotel/_delete_form.html.twig') }}
{% endblock %}

templates/hotel/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hotel index{% endblock %}

{% block body %}
    <h1>Hotel index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Nom</th>
                <th>Image</th>
                <th>Title</th>
                <th>Type</th>
                <th>Url</th>
                <th>Adult_only</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for hotel in hotels %}
            <tr>
                <td>{{ hotel.id }}</td>
                <td>{{ hotel.nom }}</td>
                <td>{{ hotel.image }}</td>
                <td>{{ hotel.title }}</td>
                <td>{{ hotel.type }}</td>
                <td>{{ hotel.url }}</td>
                <td>{{ hotel.adultOnly ? 'Yes' : 'No' }}</td>
                <td>
                    <a href="{{ path('hotel_show', {'id': hotel.id}) }}">show</a>
                    <a href="{{ path('hotel_edit', {'id': hotel.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="8">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('hotel_new') }}">Create new</a>
{% endblock %}

templates/hotel/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Hotel{% endblock %}

{% block body %}
    <h1>Create new Hotel</h1>

    {{ include('hotel/_form.html.twig') }}

    <a href="{{ path('hotel_index') }}">back to list</a>
{% endblock %}

templates/hotel/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hotel{% endblock %}

{% block body %}
    <h1>Hotel</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ hotel.id }}</td>
            </tr>
            <tr>
                <th>Nom</th>
                <td>{{ hotel.nom }}</td>
            </tr>
            <tr>
                <th>Image</th>
                <td>{{ hotel.image }}</td>
            </tr>
            <tr>
                <th>Title</th>
                <td>{{ hotel.title }}</td>
            </tr>
            <tr>
                <th>Type</th>
                <td>{{ hotel.type }}</td>
            </tr>
            <tr>
                <th>Url</th>
                <td>{{ hotel.url }}</td>
            </tr>
            <tr>
                <th>Adult_only</th>
                <td>{{ hotel.adultOnly ? 'Yes' : 'No' }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('hotel_index') }}">back to list</a>

    <a href="{{ path('hotel_edit', {'id': hotel.id}) }}">edit</a>

    {{ include('hotel/_delete_form.html.twig') }}
{% endblock %}